(()=>{
  'use strict';
  const C=window.APP_CONFIG||{};const money=new Intl.NumberFormat(C.LOCALE||'pt-BR',{style:'currency',currency:C.CURRENCY||'BRL'});
  const state={enabled:false,status:'idle',fee:0,distanceKm:null,durationMin:null,source:null,customerCoords:null,addressLabel:'',district:'',requestId:0,subtotal:0,settings:null,lastMessage:'',serverGate:null};
  const $=s=>document.querySelector(s),els={card:$('#deliveryLocationCard'),status:$('#deliveryStatus'),result:$('#deliveryResult'),distance:$('#deliveryDistance'),fee:$('#deliveryFee'),gps:$('#useLocationBtn'),addressCalc:$('#calcAddressBtn'),address:$('#customerAddress'),district:$('#customerDistrict'),send:$('#sendWhatsappBtn')};
  const dispatch=()=>document.dispatchEvent(new CustomEvent('cantinho:delivery-updated',{detail:getPublicState()}));
  function getPublicState(){return {enabled:state.enabled,status:state.status,fee:state.fee,distanceKm:state.distanceKm,source:state.source,addressLabel:state.addressLabel,district:state.district,customerCoords:state.customerCoords?state.customerCoords.slice():null,settings:state.settings,withinArea:state.status==='ready'};}
  function setStatus(text,type='info'){state.lastMessage=text;if(!els.status)return;els.status.textContent=text;els.status.className=`delivery-status ${type}`;els.status.classList.remove('hidden');}
  function setBusy(b){if(els.gps)els.gps.disabled=b;if(els.addressCalc)els.addressCalc.disabled=b;if(els.send&&state.enabled)els.send.disabled=b||state.status!=='ready';}
  function render(){if(!els.card)return;els.card.classList.toggle('delivery-ready',state.status==='ready');els.card.classList.toggle('delivery-outside',state.status==='outside');els.card.classList.toggle('delivery-error',state.status==='error'||state.status==='unavailable');if(els.result){const show=state.distanceKm!=null;els.result.classList.toggle('hidden',!show);}if(els.distance&&state.distanceKm!=null)els.distance.textContent=`${state.distanceKm.toFixed(2).replace('.',',')} km`;if(els.fee)els.fee.textContent=state.status==='ready'?money.format(state.fee):'—';if(els.send)els.send.disabled=state.enabled&&state.status!=='ready';dispatch();}
  function reset(message='Calcule a distância para liberar o envio do pedido.'){state.status='idle';state.fee=0;state.distanceKm=null;state.durationMin=null;state.source=null;state.customerCoords=null;state.addressLabel='';state.district='';if(els.result)els.result.classList.add('hidden');if(state.enabled)setStatus(message,'info');else if(els.status)els.status.classList.add('hidden');setBusy(false);render();}
  function edgeUrl(){const base=String(C.SUPABASE_URL||'').replace(/\/$/,''),name=String(C.DELIVERY_FUNCTION_NAME||'calc-delivery').trim();if(!base||!name)throw new Error('Serviço de entrega não configurado.');return `${base}/functions/v1/${encodeURIComponent(name)}`;}
  async function callEdge(body){const key=String(C.SUPABASE_PUBLISHABLE_KEY||'').trim();if(!key)throw new Error('Chave pública do Supabase não configurada.');const response=await fetch(edgeUrl(),{method:'POST',headers:{'Content-Type':'application/json','apikey':key,'x-cantinho-client':'v25'},body:JSON.stringify({...body,subtotal:state.subtotal})});let data=null;try{data=await response.json();}catch{}if(!response.ok||data?.ok===false){const code=data?.code||'',m=data?.message||data?.error||'';if(code==='ORS_NOT_CONFIGURED')throw new Error('O cálculo de entrega ainda não foi ativado no servidor.');if(code==='ADDRESS_NOT_FOUND')throw new Error('Endereço não encontrado. Confira rua, número e bairro.');if(code==='ORIGIN_BLOCKED')throw new Error('Este site não está autorizado a usar o cálculo de entrega.');if(response.status===429)throw new Error('Muitas consultas de localização. Aguarde um pouco e tente novamente.');throw new Error(typeof m==='string'&&m?m:'Não foi possível calcular a entrega agora.');}return data;}
  function normalize(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();}
  function evaluateLocal(){const s=state.settings;if(!s)return null;if(state.serverGate?.reasonCode==='DELIVERY_CLOSED')return state.serverGate;if(s.enabled===false)return {available:false,reasonCode:'DELIVERY_DISABLED',message:'O delivery está temporariamente desativado.',fee:0};const min=s.minimum_order_value==null?null:Number(s.minimum_order_value);if(min!=null&&state.subtotal+1e-9<min)return {available:false,reasonCode:'MINIMUM_ORDER',message:`Pedido mínimo para entrega: ${money.format(min)}.`,fee:0};if(state.district&&Array.isArray(s.blocked_districts)&&s.blocked_districts.some(x=>normalize(x)===normalize(state.district)))return {available:false,reasonCode:'DISTRICT_BLOCKED',message:'Este bairro está fora da área de entrega.',fee:0};if(state.distanceKm!=null&&state.distanceKm>Number(s.max_distance_km||3)+1e-9)return {available:false,reasonCode:'OUTSIDE_DISTANCE',message:`Entregamos somente até ${Number(s.max_distance_km||3).toFixed(1).replace('.',',')} km.`,fee:0};if(state.distanceKm==null)return {available:true,reasonCode:'NEEDS_ROUTE',message:'Calcule a distância para liberar o envio do pedido.',fee:0};const tiers=(Array.isArray(s.tiers)?s.tiers:[]).slice().sort((a,b)=>Number(a.up_to_km)-Number(b.up_to_km)),tier=tiers.find(t=>state.distanceKm<=Number(t.up_to_km)+1e-9);if(!tier)return {available:false,reasonCode:'NO_TIER',message:'Não há taxa configurada para esta distância.',fee:0};let fee=Number(tier.fee)||0;const free=s.free_delivery_over==null?null:Number(s.free_delivery_over);if(free!=null&&state.subtotal>=free)fee=0;return {available:true,reasonCode:'OK',message:`Entrega disponível: ${state.distanceKm.toFixed(2).replace('.',',')} km. Taxa ${money.format(fee)}.`,fee};}
  function applyEligibility(d){if(d?.settings)state.settings=d.settings;state.serverGate=d?.reasonCode==='DELIVERY_CLOSED'?d:null;const local=evaluateLocal(),v=state.serverGate||(local||d);if(!v)return;if(v.available&&state.distanceKm!=null){state.status='ready';state.fee=Number(v.fee||0);setStatus(v.message||`Entrega disponível. Taxa ${money.format(state.fee)}.`,'success');}else if(v.available){state.status='idle';state.fee=0;setStatus(v.message||'Calcule a distância para liberar o envio do pedido.','info');}else{state.status=v.reasonCode==='OUTSIDE_DISTANCE'?'outside':'unavailable';state.fee=0;setStatus(v.message||'Entrega indisponível.','error');}setBusy(false);render();}
  async function setEnabled(enabled){state.enabled=!!enabled;if(!state.enabled){reset('');return;}state.status='calculating';setStatus('Carregando regras do delivery…','loading');setBusy(true);render();const id=++state.requestId;try{const data=await callEdge({action:'settings'});if(id!==state.requestId)return;applyEligibility(data.delivery||{});}catch(e){if(id!==state.requestId)return;state.status='error';setBusy(false);setStatus(e.message||'Não foi possível carregar as regras do delivery.','error');render();}}
  function setSubtotal(v){const n=Number(v);state.subtotal=Number.isFinite(n)&&n>=0?n:0;if(!state.enabled||!state.settings)return;const wasReady=state.distanceKm!=null;const local=evaluateLocal();if(local){if(local.available&&wasReady){state.status='ready';state.fee=Number(local.fee||0);setStatus(local.message,'success');}else if(!local.available){state.status=local.reasonCode==='OUTSIDE_DISTANCE'?'outside':'unavailable';state.fee=0;setStatus(local.message,'error');}else if(!wasReady&&state.status!=='calculating'){state.status='idle';state.fee=0;setStatus(local.message,'info');}render();}}
  function invalidateManual(){if(!state.enabled||state.source!=='address'||state.status==='calculating')return;reset('O endereço foi alterado. Calcule a distância novamente.');}
  function applyResult(data,source,id){if(id!==state.requestId)return;if(!Number.isFinite(Number(data?.distanceKm)))throw new Error('O serviço não retornou uma distância válida.');state.source=source;state.distanceKm=Number(data.distanceKm);const dur=Number(data.durationMin);state.durationMin=Number.isFinite(dur)?dur:null;state.addressLabel=String(data.label||'');state.district=String(data.district||'');if(Array.isArray(data.coords)&&data.coords.length===2)state.customerCoords=data.coords.map(Number);if(data.label&&els.address&&!els.address.value.trim())els.address.value=data.label;if(data.district&&els.district&&!els.district.value.trim())els.district.value=data.district;applyEligibility(data.delivery||{});}
  function fail(e,id){if(id!==state.requestId)return;state.status='error';state.fee=0;state.distanceKm=null;state.durationMin=null;setBusy(false);setStatus(e?.message||'Não foi possível calcular a entrega.','error');render();}
  async function calculateGps(){if(!state.enabled)return;if(!navigator.geolocation){state.status='error';setStatus('Este navegador não oferece localização. Digite o endereço e calcule por ele.','error');render();return;}const id=++state.requestId;state.status='calculating';setStatus('Obtendo sua localização…','loading');setBusy(true);render();navigator.geolocation.getCurrentPosition(async pos=>{if(id!==state.requestId)return;try{const lat=Number(pos.coords.latitude),lon=Number(pos.coords.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))throw new Error('Localização inválida.');setStatus('Localização encontrada. Calculando a rota pelas ruas…','loading');const data=await callEdge({action:'gps',lat,lon});applyResult(data,'gps',id);}catch(e){fail(e,id);}},err=>{if(id!==state.requestId)return;state.status='error';state.fee=0;setBusy(false);const msg=err?.code===1?'A localização foi negada. Permita o GPS ou calcule pelo endereço.':err?.code===3?'O GPS demorou demais. Tente novamente ou use o endereço.':'Não foi possível obter sua localização. Use o endereço manual.';setStatus(msg,'error');render();},{enableHighAccuracy:true,timeout:15000,maximumAge:60000});}
  async function calculateAddress(){if(!state.enabled)return;const address=els.address?.value.trim()||'',district=els.district?.value.trim()||'';if(!address){els.address?.focus();setStatus('Digite rua e número antes de calcular.','error');return;}const id=++state.requestId;state.status='calculating';setStatus('Localizando o endereço e calculando a rota…','loading');setBusy(true);render();try{const data=await callEdge({action:'address',address,district});applyResult(data,'address',id);}catch(e){fail(e,id);}}
  function validate(){if(!state.enabled)return {ok:true};if(state.status==='ready')return {ok:true};return {ok:false,message:state.lastMessage||'Calcule a distância da entrega antes de enviar o pedido.'};}
  els.gps?.addEventListener('click',calculateGps);els.addressCalc?.addEventListener('click',calculateAddress);els.address?.addEventListener('input',invalidateManual);els.district?.addEventListener('input',invalidateManual);window.deliveryService={setEnabled,reset,validate,setSubtotal,getFee:()=>state.enabled&&state.status==='ready'?state.fee:0,getDistanceKm:()=>state.distanceKm,getDurationMin:()=>state.durationMin,getState:getPublicState,calculateGps,calculateAddress};render();
})();
