(()=>{'use strict';
const DISMISS_KEY='cantinho:pwa:dismissedAt',INSTALLED_KEY='cantinho:pwa:installed',DISMISS_DAYS=30;let deferredPrompt=null,interacted=false;
const $=id=>document.getElementById(id);const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;const isiOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);const safariIOS=()=>isiOS()&&/safari/i.test(navigator.userAgent)&&!/crios|fxios|edgios/i.test(navigator.userAgent);const dismissed=()=>{const v=Number(localStorage.getItem(DISMISS_KEY)||0);return !!v&&(Date.now()-v)<DISMISS_DAYS*86400000};const canOffer=()=>!standalone()&&(!!deferredPrompt||safariIOS());
function hide(){ $('installClientBtn')?.classList.add('hidden');$('installSuggestion')?.classList.add('hidden'); }
function safe(){return !$('cartDrawer')?.classList.contains('open')&&!document.querySelector('dialog[open]')}
function schedule(delay=4000){clearTimeout(schedule.timer);schedule.timer=setTimeout(()=>{if(!canOffer()||dismissed()||!interacted)return;if(!safe())return schedule(2500);$('installSuggestion')?.classList.remove('hidden')},delay)}
function refresh(){if(!canOffer())return hide();$('installClientBtn')?.classList.remove('hidden');if(interacted&&!dismissed())schedule()}
function iosHelp(){const d=$('iosInstallDialog');if(d&&!d.open)d.showModal()}
async function install(){ $('installSuggestion')?.classList.add('hidden');if(safariIOS())return iosHelp();if(!deferredPrompt)return;deferredPrompt.prompt();const r=await deferredPrompt.userChoice.catch(()=>({outcome:'dismissed'}));if(r.outcome==='accepted'){localStorage.setItem(INSTALLED_KEY,'1');hide()}else localStorage.setItem(DISMISS_KEY,String(Date.now()));deferredPrompt=null;refresh() }
function dismiss(){localStorage.setItem(DISMISS_KEY,String(Date.now()));$('installSuggestion')?.classList.add('hidden')}
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js?v=22',{scope:'./'}).catch(()=>{}));
addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;localStorage.removeItem(INSTALLED_KEY);refresh()});addEventListener('appinstalled',()=>{localStorage.setItem(INSTALLED_KEY,'1');localStorage.removeItem(DISMISS_KEY);deferredPrompt=null;hide()});matchMedia('(display-mode: standalone)').addEventListener?.('change',e=>{if(e.matches)hide()});
document.addEventListener('DOMContentLoaded',()=>{if(standalone()){localStorage.setItem(INSTALLED_KEY,'1');return hide()}$('installClientBtn')?.addEventListener('click',install);$('installSuggestionInstall')?.addEventListener('click',install);$('installSuggestionDismiss')?.addEventListener('click',dismiss);$('closeIosInstall')?.addEventListener('click',()=>$('iosInstallDialog')?.close());const first=e=>{if(e.target.closest('#installSuggestion,#installClientBtn,#iosInstallDialog'))return;interacted=true;refresh();document.removeEventListener('pointerdown',first,true);document.removeEventListener('keydown',first,true)};document.addEventListener('pointerdown',first,true);document.addEventListener('keydown',first,true);if(safariIOS())refresh()});
})();
