// Cantinho do Petisco — V25
// ORS_API_KEY continua somente nos Secrets do Supabase.
// Regras do delivery são lidas da tabela public.delivery_settings.

const ORS_BASE = 'https://api.heigit.org';
const RESTAURANT_COORDS: [number, number] = [-46.3526171, -23.055199]; // ORS usa [longitude, latitude]
const RESTAURANT_CITY = 'Piracaia';
const RESTAURANT_STATE = 'SP';
const ALLOWED_ORIGINS = new Set(['https://luizemsaopaulo.github.io']);
const DEFAULT_SETTINGS = {
  id: 1, enabled: true, enforce_business_hours: false, max_distance_km: 3, minimum_order_value: null, free_delivery_over: null,
  estimated_minutes_min: 30, estimated_minutes_max: 50, blocked_districts: [], tiers: [{ up_to_km: 3, fee: 5 }],
  business_hours: { '0': { enabled:true,open:'11:00',close:'22:00' }, '1': { enabled:true,open:'11:00',close:'22:00' }, '2': { enabled:true,open:'11:00',close:'22:00' }, '3': { enabled:true,open:'11:00',close:'22:00' }, '4': { enabled:true,open:'11:00',close:'22:00' }, '5': { enabled:true,open:'11:00',close:'22:00' }, '6': { enabled:true,open:'11:00',close:'22:00' } }
};
let settingsCache: { at:number, value:any } | null = null;

function cors(origin: string | null) { const allowed=origin&&(ALLOWED_ORIGINS.has(origin)||/^http:\/\/(localhost|127\\.0\\.0\\.1)(:\\d+)?$/.test(origin)); return {'Access-Control-Allow-Origin':allowed?origin!:'https://luizemsaopaulo.github.io','Access-Control-Allow-Headers':'content-type, apikey, x-cantinho-client','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}; }
function json(origin:string|null,status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers:cors(origin)});}
function originAllowed(origin:string|null){return !!origin&&(ALLOWED_ORIGINS.has(origin)||/^http:\/\/(localhost|127\\.0\\.0\\.1)(:\\d+)?$/.test(origin));}
function finite(n:unknown){return Number.isFinite(Number(n));}
function validCoords(lon:unknown,lat:unknown):[number,number]|null{if(!finite(lon)||!finite(lat))return null;const x=Number(lon),y=Number(lat);if(x < -180||x>180||y < -90||y>90)return null;if(x < -54||x > -43||y < -26||y > -19)return null;return [x,y];}
function parsePublishableKeys(){const out=new Set<string>();try{const obj=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}');for(const value of Object.values(obj))if(typeof value==='string')out.add(value);}catch{}const legacy=Deno.env.get('SUPABASE_ANON_KEY');if(legacy)out.add(legacy);return out;}
function clientKeyAllowed(req:Request){const allowed=parsePublishableKeys();if(!allowed.size)return true;return allowed.has(req.headers.get('apikey')||'');}
async function ors(path:string,init:RequestInit={}){const key=Deno.env.get('ORS_API_KEY');if(!key)throw Object.assign(new Error('ORS_API_KEY não configurada.'),{code:'ORS_NOT_CONFIGURED',status:503});const r=await fetch(`${ORS_BASE}${path}`,{...init,headers:{Authorization:key,...(init.headers||{})}});let data:any=null;try{data=await r.json();}catch{}if(!r.ok){const detail=data?.error?.message||data?.message||data?.error||`ORS ${r.status}`;throw Object.assign(new Error(typeof detail==='string'?detail:'Falha no OpenRouteService.'),{code:'ORS_ERROR',status:r.status===429?429:502});}return data;}
function addressProps(feature:any){const p=feature?.properties||{};return {label:p.label||p.name||'',district:p.neighbourhood||p.borough||p.locality||p.localadmin||''};}
async function geocodeAddress(address:string,district=''){const safeAddress=address.trim().slice(0,180),safeDistrict=district.trim().slice(0,80);if(!safeAddress)throw Object.assign(new Error('Digite um endereço.'),{code:'ADDRESS_REQUIRED',status:400});const text=[safeAddress,safeDistrict,RESTAURANT_CITY,RESTAURANT_STATE,'Brasil'].filter(Boolean).join(', ');const q=new URLSearchParams({text,size:'1','boundary.country':'BR'});const data=await ors(`/pelias/v1/search?${q}`);const f=data?.features?.[0],c=f?.geometry?.coordinates,coords=Array.isArray(c)?validCoords(c[0],c[1]):null;if(!coords)throw Object.assign(new Error('Endereço não encontrado.'),{code:'ADDRESS_NOT_FOUND',status:404});return {coords,...addressProps(f)};}
async function reverse(lon:number,lat:number){const q=new URLSearchParams({'point.lon':String(lon),'point.lat':String(lat),size:'1'});try{const data=await ors(`/pelias/v1/reverse?${q}`),f=data?.features?.[0];return f?addressProps(f):{label:'',district:''};}catch{return {label:'',district:''};}}
async function routeToCustomer(customer:[number,number]){const data=await ors('/openrouteservice/v2/directions/driving-car/geojson',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/geo+json'},body:JSON.stringify({coordinates:[RESTAURANT_COORDS,customer],instructions:false})});const summary=data?.features?.[0]?.properties?.summary,meters=Number(summary?.distance),seconds=Number(summary?.duration||0);if(!Number.isFinite(meters))throw Object.assign(new Error('Rota sem distância válida.'),{code:'ROUTE_INVALID',status:502});return {distanceKm:meters/1000,durationMin:Number.isFinite(seconds)?seconds/60:null};}
function cleanSettings(raw:any){const s={...DEFAULT_SETTINGS,...(raw||{})};s.enabled=s.enabled!==false;s.enforce_business_hours=!!s.enforce_business_hours;s.max_distance_km=Math.max(.1,Number(s.max_distance_km)||3);s.minimum_order_value=s.minimum_order_value==null?null:Math.max(0,Number(s.minimum_order_value)||0);s.free_delivery_over=s.free_delivery_over==null?null:Math.max(0,Number(s.free_delivery_over)||0);s.estimated_minutes_min=s.estimated_minutes_min==null?null:Math.max(0,Number(s.estimated_minutes_min)||0);s.estimated_minutes_max=s.estimated_minutes_max==null?null:Math.max(0,Number(s.estimated_minutes_max)||0);s.blocked_districts=Array.isArray(s.blocked_districts)?s.blocked_districts.map(String).filter(Boolean):[];s.tiers=(Array.isArray(s.tiers)?s.tiers:DEFAULT_SETTINGS.tiers).map((t:any)=>({up_to_km:Number(t?.up_to_km),fee:Number(t?.fee)})).filter((t:any)=>Number.isFinite(t.up_to_km)&&t.up_to_km>0&&Number.isFinite(t.fee)&&t.fee>=0).sort((a:any,b:any)=>a.up_to_km-b.up_to_km);if(!s.tiers.length)s.tiers=[{up_to_km:s.max_distance_km,fee:5}];s.business_hours=(s.business_hours&&typeof s.business_hours==='object')?s.business_hours:DEFAULT_SETTINGS.business_hours;return s;}
async function getSettings(){if(settingsCache&&Date.now()-settingsCache.at<5000)return settingsCache.value;const url=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_ANON_KEY')||'';if(!url||!key)return cleanSettings(null);try{const r=await fetch(`${url}/rest/v1/delivery_settings?id=eq.1&select=*`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!r.ok)throw new Error(String(r.status));const rows=await r.json();const value=cleanSettings(rows?.[0]);settingsCache={at:Date.now(),value};return value;}catch{return cleanSettings(null);}}
function normalizeText(v:string){return String(v||'').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').trim().toLowerCase();}
function nowSP(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const weekday=parts.find(p=>p.type==='weekday')?.value||'Mon',hour=parts.find(p=>p.type==='hour')?.value||'00',minute=parts.find(p=>p.type==='minute')?.value||'00';const dayMap:any={Sun:'0',Mon:'1',Tue:'2',Wed:'3',Thu:'4',Fri:'5',Sat:'6'};return {day:dayMap[weekday]||'1',time:`${hour}:${minute}`};}
function timeInWindow(now:string,open:string,close:string){if(!open||!close)return true;if(open===close)return true;if(open<close)return now>=open&&now<=close;return now>=open||now<=close;}
function evaluate(settings:any,distanceKm:number|null,district:string,subtotal:number){if(!settings.enabled)return {available:false,reasonCode:'DELIVERY_DISABLED',message:'O delivery está temporariamente desativado.',fee:0};if(settings.enforce_business_hours){const n=nowSP(),h=settings.business_hours?.[n.day];if(!h?.enabled||!timeInWindow(n.time,String(h.open||''),String(h.close||'')))return {available:false,reasonCode:'DELIVERY_CLOSED',message:'O delivery está fechado neste horário.',fee:0};}if(settings.minimum_order_value!=null&&subtotal+1e-9<settings.minimum_order_value)return {available:false,reasonCode:'MINIMUM_ORDER',message:`Pedido mínimo para entrega: R$ ${settings.minimum_order_value.toFixed(2).replace('.',',')}.`,fee:0};const nd=normalizeText(district);if(nd&&settings.blocked_districts.some((x:string)=>normalizeText(x)===nd))return {available:false,reasonCode:'DISTRICT_BLOCKED',message:'Este bairro está fora da área de entrega.',fee:0};if(distanceKm!=null&&distanceKm>settings.max_distance_km+1e-9)return {available:false,reasonCode:'OUTSIDE_DISTANCE',message:`Entregamos somente até ${settings.max_distance_km.toFixed(1).replace('.',',')} km.`,fee:0};let fee=0;if(distanceKm!=null){const tier=settings.tiers.find((t:any)=>distanceKm<=t.up_to_km+1e-9);if(!tier)return {available:false,reasonCode:'NO_TIER',message:'Não há taxa configurada para esta distância.',fee:0};fee=tier.fee;}if(settings.free_delivery_over!=null&&subtotal>=settings.free_delivery_over)fee=0;return {available:true,reasonCode:'OK',message:'Entrega disponível.',fee};}
function publicSettings(s:any){return {enabled:s.enabled,enforce_business_hours:s.enforce_business_hours,max_distance_km:s.max_distance_km,minimum_order_value:s.minimum_order_value,free_delivery_over:s.free_delivery_over,blocked_districts:s.blocked_districts,tiers:s.tiers,business_hours:s.business_hours};}

Deno.serve(async(req)=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS'){if(!originAllowed(origin))return json(origin,403,{ok:false,code:'ORIGIN_BLOCKED',message:'Origem não autorizada.'});return new Response(null,{status:204,headers:cors(origin)});}if(req.method!=='POST')return json(origin,405,{ok:false,code:'METHOD_NOT_ALLOWED',message:'Use POST.'});if(!originAllowed(origin))return json(origin,403,{ok:false,code:'ORIGIN_BLOCKED',message:'Origem não autorizada.'});if(!clientKeyAllowed(req))return json(origin,401,{ok:false,code:'BAD_CLIENT_KEY',message:'Cliente não autorizado.'});try{const body=await req.json(),action=String(body?.action||''),subtotal=Math.max(0,Number(body?.subtotal)||0),settings=await getSettings();if(action==='settings'){const delivery=evaluate(settings,null,'',subtotal);return json(origin,200,{ok:true,delivery:{...delivery,settings:publicSettings(settings)}});}let coords:[number,number],info={label:'',district:''};if(action==='gps'){const c=validCoords(body?.lon,body?.lat);if(!c)return json(origin,400,{ok:false,code:'BAD_COORDS',message:'Coordenadas inválidas.'});coords=c;const [route,reverseInfo]=await Promise.all([routeToCustomer(coords),reverse(coords[0],coords[1])]);const delivery=evaluate(settings,route.distanceKm,reverseInfo.district,subtotal);return json(origin,200,{ok:true,coords,...reverseInfo,...route,delivery:{...delivery,settings:publicSettings(settings)}});}if(action==='address'){const found=await geocodeAddress(String(body?.address||''),String(body?.district||''));coords=found.coords;info={label:found.label,district:found.district};const route=await routeToCustomer(coords),delivery=evaluate(settings,route.distanceKm,info.district,subtotal);return json(origin,200,{ok:true,coords,...info,...route,delivery:{...delivery,settings:publicSettings(settings)}});}return json(origin,400,{ok:false,code:'BAD_ACTION',message:'Ação inválida.'});}catch(e:any){const status=Number(e?.status)||500,code=String(e?.code||'SERVER_ERROR');const safeMessage=code==='ORS_NOT_CONFIGURED'?'Serviço de rota não configurado.':code==='ORS_ERROR'?'Serviço de rota temporariamente indisponível.':(e?.message||'Erro interno.');return json(origin,status,{ok:false,code,message:safeMessage});}});
